import React, { useState } from 'react';
import { AppContextType, AppState, AvatarState } from '../types';
import { generateImageFromPrompt } from '../services/geminiService';
import { SparklesIcon } from './icons/SparklesIcon';
import { PhotoIcon } from './icons/PhotoIcon';

interface ImageGenerationViewProps {
    context: AppContextType;
}

const ImageGenerationView: React.FC<ImageGenerationViewProps> = ({ context }) => {
    const { setAppState, setAvatarState } = context;
    const [prompt, setPrompt] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [imageUrl, setImageUrl] = useState<string | null>(null);

    const handleGenerate = async () => {
        if (!prompt.trim()) {
            setError("Please enter a prompt to generate an image.");
            return;
        }
        setIsLoading(true);
        setError(null);
        setImageUrl(null);
        setAvatarState(AvatarState.THINKING);

        try {
            const base64Image = await generateImageFromPrompt(prompt);
            setImageUrl(`data:image/png;base64,${base64Image}`);
        } catch (err: any) {
            setError(err.message || "Failed to generate image. Please try again.");
        } finally {
            setIsLoading(false);
            setAvatarState(AvatarState.IDLE);
        }
    };

    return (
        <div className="flex flex-col h-full animate-fade-in">
            <h2 className="text-3xl font-bold text-[var(--color-primary)] mb-4">Image Playground</h2>
            <p className="text-[var(--color-text-muted)] mb-6">
                Let your imagination run wild! Describe anything you want to see, and StudyBuddy AI will create it for you.
            </p>

            <div className="flex flex-col flex-grow gap-6">
                {/* Prompt Input */}
                <div>
                    <label htmlFor="image-prompt" className="block text-lg font-semibold text-[var(--color-text-secondary)] mb-2">Your Prompt:</label>
                    <textarea
                        id="image-prompt"
                        rows={3}
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="e.g., A friendly robot teaching math to a group of curious animals in a futuristic classroom"
                        className="w-full bg-[var(--color-surface-light)] border border-[var(--color-border)] rounded-lg p-3 text-[var(--color-text-primary)] focus:ring-[var(--color-primary)] focus:border-[var(--color-primary)]"
                        disabled={isLoading}
                    />
                </div>

                {/* Image Display Area */}
                <div className="flex-grow w-full bg-[var(--color-background)] rounded-lg flex items-center justify-center p-4 relative aspect-square">
                    {isLoading && (
                        <div className="flex flex-col items-center text-center">
                            <SparklesIcon className="w-16 h-16 text-[var(--color-primary)] animate-pulse" />
                            <p className="mt-4 text-[var(--color-text-secondary)]">StudyBuddy AI is creating your masterpiece...</p>
                        </div>
                    )}
                    {!isLoading && imageUrl && (
                        <img src={imageUrl} alt="Generated by AI" className="max-w-full max-h-full object-contain rounded-md" />
                    )}
                    {!isLoading && !imageUrl && (
                        <div className="text-center text-[var(--color-text-muted)]">
                            <PhotoIcon className="w-24 h-24 mx-auto" />
                            <p className="mt-2">Your generated image will appear here</p>
                        </div>
                    )}
                </div>
            </div>

            {error && <p className="text-[var(--color-danger)] text-center text-sm mt-4">{error}</p>}

            <div className="mt-6 flex justify-between items-center">
                <button
                    onClick={() => setAppState(AppState.DASHBOARD)}
                    className="px-6 py-2 bg-[var(--color-surface-light)] hover:bg-[var(--color-surface-lighter)] rounded-lg font-semibold"
                >
                    Back to Dashboard
                </button>
                <button
                    onClick={handleGenerate}
                    disabled={isLoading || !prompt.trim()}
                    className="px-8 py-3 bg-[var(--color-primary-action)] hover:bg-[var(--color-primary-hover)] rounded-lg font-bold text-lg flex items-center gap-2 disabled:bg-[var(--color-surface-lighter)] disabled:cursor-not-allowed"
                >
                    {isLoading ? (
                        <>
                            <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                            Generating...
                        </>
                    ) : (
                        <>
                            <SparklesIcon className="w-6 h-6" />
                            Generate
                        </>
                    )}
                </button>
            </div>
        </div>
    );
};

export default ImageGenerationView;